# Jykell configuration
markdown: kramdown
highlighter: rouge
language: 'en-us'

# Website info
name: 'Corey Mines Design Portfolio'
description: "Design, Development and UX portfolio by Corey Mines living in Boise, ID"
url: https://coreymines.design
short_url: 'coreymines.design'
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: 
siteurl: 
canonicalurl: https://coreymines.design

# Permalinks
permalink: /blog/:title.html
# permalink: /author/:username
# permalink: /tag/:tag

# gems and other configs

plugins:
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-assets
  - jekyll-minifier 

paginate_path: "/blog/:title.html"

# Pagination Settings
pagination:
  enabled: true
  per_page: 8
  # permalink: '/blog/:title.html'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

  # Produces a cleaner folder structure when using categories
permalink: /blog/:title

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: https-coreymines-design

url: "https://coreymines.design" # the base hostname & protocol for your site

exclude: ['node_modules']

include: ['_pages']

relative_permalinks: false